// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXxzktI-691QwCR3FTEZsNULa-mP3jSSc',
    appId: '1:491196931260:web:36fc9a5ad3eb5c34e5c4b9',
    messagingSenderId: '491196931260',
    projectId: 'activity12-inventorymanagement',
    authDomain: 'activity12-inventorymanagement.firebaseapp.com',
    storageBucket: 'activity12-inventorymanagement.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArvjTouWOIrm1Xue5Yq17mnlFFgzYtUY0',
    appId: '1:491196931260:android:5d18ed5c9948f064e5c4b9',
    messagingSenderId: '491196931260',
    projectId: 'activity12-inventorymanagement',
    storageBucket: 'activity12-inventorymanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTUWYie5LzVhetxgcxCRC2I8fcjYnrQI',
    appId: '1:491196931260:ios:47545d9f851bafcae5c4b9',
    messagingSenderId: '491196931260',
    projectId: 'activity12-inventorymanagement',
    storageBucket: 'activity12-inventorymanagement.firebasestorage.app',
    iosBundleId: 'com.example.inventorymanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOTUWYie5LzVhetxgcxCRC2I8fcjYnrQI',
    appId: '1:491196931260:ios:47545d9f851bafcae5c4b9',
    messagingSenderId: '491196931260',
    projectId: 'activity12-inventorymanagement',
    storageBucket: 'activity12-inventorymanagement.firebasestorage.app',
    iosBundleId: 'com.example.inventorymanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXxzktI-691QwCR3FTEZsNULa-mP3jSSc',
    appId: '1:491196931260:web:8fe62e73ee22d734e5c4b9',
    messagingSenderId: '491196931260',
    projectId: 'activity12-inventorymanagement',
    authDomain: 'activity12-inventorymanagement.firebaseapp.com',
    storageBucket: 'activity12-inventorymanagement.firebasestorage.app',
  );
}
